# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      # We want setuptools_scm to report the correct version, see
      # https://github.com/readthedocs/readthedocs.org/issues/2144#issuecomment-1695425010
      # and https://docs.readthedocs.io/en/latest/build-customization.html#avoid-having-a-dirty-git-index
      - git update-index --assume-unchanged docs/conf.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install the required dependencies
python:
  install:
    - requirements: docs/requirements.txt
