os: linux
dist: jammy
language: python
addons:
  apt:
    packages:
    - libmms0
jobs:
  include:
    - python: &python_main_version 3.11
      env:
        TOXENV: docs,black,flake8,isort,mypy,pylint
        TOX_PARALLEL: "-p"
    - python: 3.7
      env:
        TOXENV: py37
    - python: 3.8
      env:
        TOXENV: py38
    - python: 3.9
      env:
        TOXENV: py39
    - python: 3.10
      env:
        TOXENV: py310
    - python: 3.11
      env:
        TOXENV: py311
    - python: pypy3
      env:
        TOXENV: pypy3
    - os: osx
      # Not required but makes Travis' output prettier
      language: generic
      env:
        MB_PYTHON_VERSION: 3.7
        TOXENV: py37
    - os: osx
      language: generic
      env:
        MB_PYTHON_VERSION: 3.8
        TOXENV: py38
    - os: osx
      language: generic
      env:
        MB_PYTHON_VERSION: 3.9
        TOXENV: py39
    - os: osx
      language: generic
      env:
        MB_PYTHON_VERSION: 3.10
        TOXENV: py310
    - os: osx
      language: generic
      env:
        MB_PYTHON_VERSION: 3.11
        TOXENV: py311
before_install: |
  if [ $TRAVIS_OS_NAME == osx ]; then
    git clone https://github.com/matthew-brett/multibuild
    touch config.sh # required by the multibuild project
    source multibuild/common_utils.sh
    source multibuild/travis_steps.sh
    before_install
    curl https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/MediaInfo_DLL_${MEDIAINFO_VERSION}_Mac_x86_64+arm64.tar.bz2 | tar xj MediaInfoLib/libmediainfo.0.dylib MediaInfoLib/License.html
    # Required for tests to pass with tox
    cp MediaInfoLib/libmediainfo.0.dylib /usr/local/lib
    mv MediaInfoLib/libmediainfo.0.dylib pymediainfo
    mv MediaInfoLib/License.html docs
  else
    pushd /tmp
    libzen_deb=libzen0v5_${LIBZEN_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    mediainfo_deb=libmediainfo0v5_${MEDIAINFO_VERSION}-1_amd64.xUbuntu_${UBUNTU_VERSION}.deb
    curl -O https://mediaarea.net/download/binary/libzen0/${LIBZEN_VERSION}/${libzen_deb}
    curl -O https://mediaarea.net/download/binary/libmediainfo0/${MEDIAINFO_VERSION}/${mediainfo_deb}
    sudo dpkg -i ${libzen_deb} ${mediainfo_deb}
    popd
  fi
  pip install tox
script: "tox $TOX_PARALLEL"
notifications:
  email:
    on_success: change
    on_failure: change
after_success: |
  if [[ $TRAVIS_TAG ]]; then
    if [[ $TRAVIS_OS_NAME == osx && $MB_PYTHON_VERSION == $PYTHON_MAIN_VERSION ]]; then
      pip install wheel twine
      python setup.py bdist_wheel
      twine upload --skip-existing -u sbraz dist/*.whl
    # We only want to upload distributions from environments where
    # the actual test suite runs, and not just QA stuff like pylint & friends,
    # so we make sure it's a py-something tox environment
    elif [[ $TRAVIS_OS_NAME == linux && $TRAVIS_PYTHON_VERSION == $PYTHON_MAIN_VERSION && $TOXENV == py?? ]]; then
      # sdists generated on OSX have a problem with the accented test file
      # https://github.com/sbraz/pymediainfo/issues/67
      python setup.py sdist
      pip install twine
      twine upload --skip-existing -u sbraz dist/*.gz
    fi
  fi
env:
  global:
    # TWINE_PASSWORD
    - secure: "WjxnZjhgG7SCFbtYNbCAv935y3GG1CBHKJZbjSag9dBNg41OF98Q4PjnK6KxQ68Avfsv8mTGn8FbbGyXU4J033khynMCDOPMo0MAKPVYTaon3GKXf9triyzuuFty5U0kydJyqQdiqpkJPgkOou19s/x1AesfBthUswS51kyWdeg="
    - MEDIAINFO_VERSION: 22.09
    - LIBZEN_VERSION: 0.4.39
    - UBUNTU_VERSION: 22.04
    - PYTHON_MAIN_VERSION: *python_main_version
    - TOX_PARALLEL_NO_SPINNER: 1
